version: 2
jobs:
  build:
    docker:
        - image: "debian:stretch"
     steps:
      - checkout
      - run: mkdir build
      - run: sudo apt-get update && sudo apt-get install -y openmpi-bin
      - run: cd build && make
  test:
    docker:
        - image: "debian:stretch"
    steps:
      - checkout
      - run: mkdir build
      - run: sudo apt-get update && sudo apt-get install -y openmpi-bin
      - run: cd build && make tests
      - run: cd build && make check
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
